# Generated by Django 6.1 on 2026-08-25 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, unique=True, verbose_name='Disciplina')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
            ],
            options={
                'verbose_name': 'Disciplina',
                'verbose_name_plural': 'Disciplinas',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='EtapaEnsino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Etapa de Ensino')),
            ],
            options={
                'verbose_name': 'Etapa de Ensino',
                'verbose_name_plural': 'Etapas de Ensino',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='SerieAno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Série/Ano')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('etapa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='series', to='cadastros.etapaensino', verbose_name='Etapa de Ensino')),
            ],
            options={
                'verbose_name': 'Série/Ano',
                'verbose_name_plural': 'Séries/Anos',
                'ordering': ['etapa', 'ordem'],
            },
        ),
        migrations.CreateModel(
            name='SerieDisciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativa', models.BooleanField(default=True, verbose_name='Ativa')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='series', to='cadastros.disciplina', verbose_name='Disciplina')),
                ('serie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disciplinas', to='cadastros.serieano', verbose_name='Série/Ano')),
            ],
            options={
                'verbose_name': 'Disciplina por Série',
                'verbose_name_plural': 'Disciplinas por Série',
                'ordering': ['serie', 'disciplina'],
            },
        ),
        migrations.AddConstraint(
            model_name='serieano',
            constraint=models.UniqueConstraint(fields=('etapa', 'nome'), name='serie_unica_por_etapa'),
        ),
        migrations.AddConstraint(
            model_name='seriedisciplina',
            constraint=models.UniqueConstraint(fields=('serie', 'disciplina'), name='disciplina_unica_por_serie'),
        ),
    ]
