# Generated by Django 6.1 on 2026-09-03 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaConhecimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, unique=True, verbose_name='Área do Conhecimento')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('ativa', models.BooleanField(default=True, verbose_name='Ativa')),
            ],
            options={
                'verbose_name': 'Área do Conhecimento',
                'verbose_name_plural': 'Áreas do Conhecimento',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.AddField(
            model_name='disciplina',
            name='area_conhecimento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='disciplinas', to='cadastros.areaconhecimento', verbose_name='Área do Conhecimento'),
        ),
        migrations.CreateModel(
            name='Competencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=50, verbose_name='Código')),
                ('descricao', models.TextField(verbose_name='Competência')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('ativa', models.BooleanField(default=True, verbose_name='Ativa')),
                ('area_conhecimento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='competencias', to='cadastros.areaconhecimento', verbose_name='Área do Conhecimento')),
                ('disciplina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='competencias', to='cadastros.disciplina', verbose_name='Disciplina')),
                ('etapa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='competencias', to='cadastros.etapaensino', verbose_name='Etapa de Ensino')),
            ],
            options={
                'verbose_name': 'Competência',
                'verbose_name_plural': 'Competências',
                'ordering': ['etapa', 'ordem', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Habilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=50, verbose_name='Código')),
                ('descricao', models.TextField(verbose_name='Habilidade')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('ativa', models.BooleanField(default=True, verbose_name='Ativa')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='habilidades', to='cadastros.disciplina', verbose_name='Disciplina')),
                ('etapa_origem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='habilidades_origem', to='cadastros.etapaensino', verbose_name='Etapa de Origem')),
                ('serie_origem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='habilidades_origem', to='cadastros.serieano', verbose_name='Série/Ano de Origem')),
            ],
            options={
                'verbose_name': 'Habilidade',
                'verbose_name_plural': 'Habilidades',
                'ordering': ['disciplina', 'etapa_origem', 'serie_origem__ordem', 'ordem', 'id'],
            },
        ),
    ]
