# Generated by Django 6.1 on 2026-09-11 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_areaconhecimento_disciplina_area_conhecimento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetenciaComumItinerario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=50, verbose_name='Código')),
                ('descricao', models.TextField(verbose_name='Competência Comum do Itinerário Formativo')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('ativa', models.BooleanField(default=True, verbose_name='Ativa')),
            ],
            options={
                'verbose_name': 'Competência Comum do Itinerário Formativo',
                'verbose_name_plural': 'Competências Comuns dos Itinerários Formativos',
                'ordering': ['ordem', 'id'],
            },
        ),
    ]
