# Generated by Django 6.1 on 2026-09-14 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0003_competenciacomumitinerario'),
    ]

    operations = [
        migrations.CreateModel(
            name='CriterioAvaliacaoCurriculoDigitalEM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(verbose_name='Critério de Avaliação')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Critério de Avaliação - Currículo Digital EM',
                'verbose_name_plural': 'Critérios de Avaliação - Currículo Digital EM',
                'ordering': ['ordem', 'id'],
            },
        ),
        migrations.CreateModel(
            name='InstrumentoAvaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255, unique=True, verbose_name='Instrumento de Avaliação')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Instrumento de Avaliação',
                'verbose_name_plural': 'Instrumentos de Avaliação',
                'ordering': ['ordem', 'descricao'],
            },
        ),
        migrations.CreateModel(
            name='ObjetivoAprendizagemIFAGeral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(verbose_name='Objetivo Geral de Aprendizagem IFA')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Objetivo Geral de Aprendizagem IFA',
                'verbose_name_plural': 'Objetivos Gerais de Aprendizagem IFA',
                'ordering': ['ordem', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RecursoPedagogico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255, unique=True, verbose_name='Recurso Pedagógico')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Recurso Pedagógico',
                'verbose_name_plural': 'Recursos Pedagógicos',
                'ordering': ['ordem', 'descricao'],
            },
        ),
        migrations.CreateModel(
            name='Referencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(verbose_name='Referência')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('ativa', models.BooleanField(default=True, verbose_name='Ativa')),
            ],
            options={
                'verbose_name': 'Referência',
                'verbose_name_plural': 'Referências',
                'ordering': ['ordem', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ObjetivoAprendizagemIFAEspecifico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(verbose_name='Objetivo Específico de Aprendizagem IFA')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('objetivo_geral', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='objetivos_especificos', to='cadastros.objetivoaprendizagemifageral', verbose_name='Objetivo Geral')),
            ],
            options={
                'verbose_name': 'Objetivo Específico de Aprendizagem IFA',
                'verbose_name_plural': 'Objetivos Específicos de Aprendizagem IFA',
                'ordering': ['objetivo_geral__ordem', 'ordem', 'id'],
            },
        ),
    ]
