# Generated by Django 6.1 on 2026-09-17 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0004_criterioavaliacaocurriculodigitalem_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='habilidade',
            options={'ordering': ['etapa_origem', 'ordem', 'id'], 'verbose_name': 'Habilidade', 'verbose_name_plural': 'Habilidades'},
        ),
        migrations.AddField(
            model_name='habilidade',
            name='area_conhecimento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='habilidades', to='cadastros.areaconhecimento', verbose_name='Área do Conhecimento'),
        ),
        migrations.AlterField(
            model_name='habilidade',
            name='disciplina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='habilidades', to='cadastros.disciplina', verbose_name='Disciplina'),
        ),
    ]
