# Generated by Django 6.1 on 2026-09-24 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0005_alter_habilidade_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habilidade',
            name='area_conhecimento',
        ),
        migrations.AddField(
            model_name='habilidade',
            name='competencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='habilidades', to='cadastros.competencia', verbose_name='Competência'),
        ),
    ]
