# Generated by Django 6.1 on 2026-09-24 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0007_escola_professor'),
    ]

    operations = [
        migrations.CreateModel(
            name='HabilidadeCurriculoDigital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, verbose_name='Código')),
                ('descricao', models.TextField(verbose_name='Habilidade')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('ativa', models.BooleanField(default=True, verbose_name='Ativa')),
                ('etapa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='habilidades_curriculo_digital', to='cadastros.etapaensino', verbose_name='Etapa de Ensino')),
                ('serie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='habilidades_curriculo_digital', to='cadastros.serieano', verbose_name='Série/Ano')),
            ],
            options={
                'verbose_name': 'Habilidade do Currículo Digital',
                'verbose_name_plural': 'Habilidades do Currículo Digital',
                'ordering': ['etapa', 'serie', 'ordem', 'codigo'],
            },
        ),
    ]
