# Generated by Django 6.1 on 2026-09-24 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastros', '0007_escola_professor'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanejamentoMensal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.PositiveSmallIntegerField(verbose_name='Mês')),
                ('ano', models.PositiveSmallIntegerField(verbose_name='Ano')),
                ('quantidade_aulas', models.PositiveSmallIntegerField(verbose_name='Quantidade de Aulas')),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('FINALIZADO', 'Finalizado')], default='RASCUNHO', max_length=15, verbose_name='Status')),
                ('outras_habilidades', models.TextField(blank=True, verbose_name='Outras Habilidades')),
                ('objetos_conhecimento', models.TextField(blank=True, verbose_name='Objetos de Conhecimento')),
                ('metodologia', models.TextField(blank=True, verbose_name='Metodologia')),
                ('habilidades_recomposicao', models.TextField(blank=True, verbose_name='Habilidades para Recomposição')),
                ('caminho_metodologico_recomposicao', models.TextField(blank=True, verbose_name='Caminho Metodológico da Recomposição')),
                ('outro_recurso_pedagogico', models.TextField(blank=True, verbose_name='Outro Recurso Pedagógico')),
                ('outro_instrumento_avaliacao', models.TextField(blank=True, verbose_name='Outro Instrumento de Avaliação')),
                ('outra_referencia', models.TextField(blank=True, verbose_name='Outra Referência')),
                ('nome_projeto_integrador', models.CharField(blank=True, max_length=255, verbose_name='Nome do Projeto Integrador')),
                ('caminho_metodologico_projeto', models.TextField(blank=True, verbose_name='Caminho Metodológico do Projeto Integrador')),
                ('quantidade_aulas_ifa', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Quantidade de Aulas IFA')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('competencias', models.ManyToManyField(blank=True, related_name='planejamentos', to='cadastros.competencia', verbose_name='Competências')),
                ('competencias_comuns_ifa', models.ManyToManyField(blank=True, related_name='planejamentos', to='cadastros.competenciacomumitinerario', verbose_name='Competências Comuns dos Itinerários Formativos')),
                ('criterios_avaliacao_em', models.ManyToManyField(blank=True, related_name='planejamentos', to='cadastros.criterioavaliacaocurriculodigitalem', verbose_name='Critérios de Avaliação - Currículo Digital EM')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planejamentos', to='cadastros.disciplina', verbose_name='Disciplina')),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planejamentos', to='cadastros.escola', verbose_name='Escola')),
                ('habilidades', models.ManyToManyField(blank=True, related_name='planejamentos', to='cadastros.habilidade', verbose_name='Habilidades')),
                ('instrumentos_avaliacao', models.ManyToManyField(blank=True, related_name='planejamentos', to='cadastros.instrumentoavaliacao', verbose_name='Instrumentos de Avaliação')),
                ('objetivos_ifa_especificos', models.ManyToManyField(blank=True, related_name='planejamentos', to='cadastros.objetivoaprendizagemifaespecifico', verbose_name='Objetivos Específicos de Aprendizagem IFA')),
                ('objetivos_ifa_gerais', models.ManyToManyField(blank=True, related_name='planejamentos', to='cadastros.objetivoaprendizagemifageral', verbose_name='Objetivos Gerais de Aprendizagem IFA')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planejamentos', to='cadastros.professor', verbose_name='Professor')),
                ('recursos_pedagogicos', models.ManyToManyField(blank=True, related_name='planejamentos', to='cadastros.recursopedagogico', verbose_name='Recursos Pedagógicos')),
                ('referencias', models.ManyToManyField(blank=True, related_name='planejamentos', to='cadastros.referencia', verbose_name='Referências')),
                ('serie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planejamentos', to='cadastros.serieano', verbose_name='Série/Ano')),
            ],
            options={
                'verbose_name': 'Planejamento Mensal',
                'verbose_name_plural': 'Planejamentos Mensais',
                'ordering': ['-ano', '-mes', 'escola', 'serie', 'disciplina'],
                'constraints': [models.UniqueConstraint(fields=('professor', 'escola', 'serie', 'disciplina', 'mes', 'ano'), name='planejamento_mensal_unico')],
            },
        ),
    ]
