# Generated by Django 6.1 on 2026-09-24 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0008_habilidadecurriculodigital'),
        ('planejamentos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='planejamentomensal',
            name='habilidades_curriculo_digital',
            field=models.ManyToManyField(blank=True, related_name='planejamentos', to='cadastros.habilidadecurriculodigital', verbose_name='Habilidades do Currículo Digital'),
        ),
    ]
