# Generated by Django 6.1 on 2026-09-24 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planejamentos', '0002_planejamentomensal_habilidades_curriculo_digital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planejamentomensal',
            name='outras_habilidades',
            field=models.TextField(blank=True, verbose_name='Outras Habilidades do Currículo Digital'),
        ),
    ]
