# Generated by Django 6.1 on 2026-09-24 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planejamentos', '0003_alter_planejamentomensal_outras_habilidades'),
    ]

    operations = [
        migrations.AddField(
            model_name='planejamentomensal',
            name='outras_habilidades_curriculo_digital',
            field=models.TextField(blank=True, verbose_name='Outras Habilidades do Currículo Digital'),
        ),
        migrations.AlterField(
            model_name='planejamentomensal',
            name='outras_habilidades',
            field=models.TextField(blank=True, verbose_name='Outras Habilidades'),
        ),
    ]
