# Generated by Django 6.1 on 2026-09-28 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planejamentos', '0004_planejamentomensal_outras_habilidades_curriculo_digital_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planejamentomensal',
            name='metodologia',
            field=models.TextField(blank=True, verbose_name='Caminho Metodológico'),
        ),
    ]
